// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XxWwJeVGn8JleuRKHkKFJByPkIPCFUI',
    appId: '1:901036982016:web:2ebd388f15579f48f1fde5',
    messagingSenderId: '901036982016',
    projectId: 'tunisia-coride',
    authDomain: 'tunisia-coride.firebaseapp.com',
    storageBucket: 'tunisia-coride.firebasestorage.app',
    measurementId: 'G-Q4W19QRHKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDBsJa01ccQGqM_SO8t-55XHDSBLZWh8',
    appId: '1:901036982016:android:5bbdcbba1595a2cff1fde5',
    messagingSenderId: '901036982016',
    projectId: 'tunisia-coride',
    storageBucket: 'tunisia-coride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVSKNRLgA9On1tf7kC-yWy-cvZwB-yEw',
    appId: '1:901036982016:ios:7c0802bf30cc621ff1fde5',
    messagingSenderId: '901036982016',
    projectId: 'tunisia-coride',
    storageBucket: 'tunisia-coride.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvVSKNRLgA9On1tf7kC-yWy-cvZwB-yEw',
    appId: '1:901036982016:ios:7c0802bf30cc621ff1fde5',
    messagingSenderId: '901036982016',
    projectId: 'tunisia-coride',
    storageBucket: 'tunisia-coride.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XxWwJeVGn8JleuRKHkKFJByPkIPCFUI',
    appId: '1:901036982016:web:a72f7f34e6b6293df1fde5',
    messagingSenderId: '901036982016',
    projectId: 'tunisia-coride',
    authDomain: 'tunisia-coride.firebaseapp.com',
    storageBucket: 'tunisia-coride.firebasestorage.app',
    measurementId: 'G-GB600C0XXD',
  );

}